env_database: &env_database
  database: <%= RAILS_ROOT.sub(/\A.*\/([^\/]+)\/?\z/, '\1') %>_<%= RAILS_ENV %>
  host: <%= `hostname` %>
  username: <%= `whoami` %>

sqlite3: &sqlite3
  adapter: sqlite3
  database: db/<%= RAILS_ENV %>.sqlite3
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  <<: *env_database

mysql: &mysql
  adapter: mysql
  encoding: utf8
  <<: *env_database

development:
  <<: *sqlite3

test:
  <<: *sqlite3
  database: ":memory:"
  schema: automigrate

benchmark:
  <<: *postgresql

production:
  <<: *postgresql

